# k8s/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: task-scheduler
spec:
  selector:
    app: task-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
